-- tudo aqui dentro o spring ja sobe

INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (100, 'Comick books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (102, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (103, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (100, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (101, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAIABLE, CREATED_AT) VALUES (100, 'Crise nas Infinitas Terras', 100, 100, 10, current_timestamp);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAIABLE, CREATED_AT) VALUES (102, 'Interestelar', 101, 102, 5, current_timestamp);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAIABLE, CREATED_AT) VALUES (103, 'Harry Potter e a Pedra Filosofal', 101, 103, 3, current_timestamp);
