-- tudo aqui dentro o spring ja sobe

INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'Comick books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (2, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAIABLE) VALUES (1, 'Crise nas Infinitas Terras', 1, 1, 10);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAIABLE) VALUES (2, 'Interestelar', 2, 2, 5);
INSERT INTO PRODUCT (ID, NAME, FK_SUPPLIER, FK_CATEGORY, QUANTITY_AVAIABLE) VALUES (3, 'Harry Potter e a Pedra Filosofal', 2, 3, 3);
